### ISSUE TITLE
[serializers] Merging fields "req" and "res" into one when printing

### ISSUE THREAD

**Issue by kenptr** [pinojs/pino-http#124]
Hi, great work on this project!

I want to print logs to GCP Stackdriver in this format https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#httprequest

```yaml
{
 httpRequest: {
  "requestMethod": string, // extracted from req
  "requestUrl": string,
  "requestSize": string,
  "status": integer,  // extracted from res
  "responseSize": string,
  "userAgent": string,
  "remoteIp": string,
  "serverIp": string,
  "referer": string,
  "latency": string,
  "cacheLookup": boolean,
  "cacheHit": boolean,
  "cacheValidatedWithOriginServer": boolean,
  "cacheFillBytes": string,
  "protocol": string
 }
}
```

As you can see, both `res` and `req` values should be in one field. I tried some experimenting and reading the `pino-http` source code, but couldn't do it. Is it possible or if not, can we add support for it?

I also noticed that pino's `formatters.log` function doesnt' receive req, res values. And req/res is added after `formatters.log` is called, because of this I cannot fully format the final JSON. How does everyone else solve this, ideas?
