### ISSUE TITLE
Migrate to Github Actions

### ISSUE THREAD

**Issue by mcollina** [pinojs/pino-http#91]
As titled

**Comment by gkampitakis** [comment]
Can I give it a try ? From what I ve seen your travis CI pipeline just runs test on merge and pr right ? 
I am not really sure though about this: 
```yaml
env:
  global:
    secure: <>
```
